sh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

# provides a helper function to return a URL pattern for serving files in debug mode:
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admyn/', admin.site.urls),

    # path('account/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    # allows login at api root
    path('api-auth/', include('rest_framework.urls')),
    path('', include('frontend.urls')),
    # path('', TemplateView.as_view(template_name="index.html")),
    # path('front/' '/frontend/index.html')

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        # this will enable serving images in debug mode by url

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

obs/models.py
'''
Significant changes to models.py will occur once data from atlasbiowork is loaded for the transition. Likely the hierarchical parent-child data model for Observations will be discarded in favor of better query capability by site, etc. Soil sample obs can be extended with an analysis adjunct, or else correlated by site, sampleID, and date.
'''

from django.contrib.gis.db import models
from django.contrib.gis.db.models import PointField  # experimental
from django.contrib.postgres.fields import JSONField
from django.conf import settings
import xlsconv

XLSCONV_TEMPLATE = settings.BASE_DIR + '/xlsconv_templates/%s.html'


class Site(models.Model):
    name = models.CharField(max_length=100, unique=False)
    geometry = models.GeometryField(srid=4326)
    accuracy = models.FloatField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/sites/%i/" % self.id

    class Meta:
        ordering = ['-pk']
        verbose_name_plural = 'sites'


class ObservationType(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=30, null=True, blank=True,
                            help_text='No spaces, will be the PascalCase name of the Vue component, such as PastureMove')
    icon = models.ImageField(upload_to='forms')
    description = models.TextField(
        max_length=200, null=True, blank=False, help_text='briefly describe purpose and function')
    author = models.ForeignKey(
        'users.CustomUser', null=True, blank=True, on_delete=models.SET_NULL)
    xlsform = models.FileField(upload_to='forms', null=True, blank=True)
    form_json = JSONField(null=True, blank=True)

    # def save(self, *args, **kwargs):
    #     if self.xlsform:
    #         try:
    #             self.form_json = xlsconv.parse_xls(self.xlsform)
    #         except Exception as e:
    #             self.edit_html = "Error parsing form: %s" % e
    #             self.detail_html = "Error parsing form: %s" % e
    #         else:
    #             if not self.edit_html:
    #                 self.edit_html = self.generate_html('edit')
    #             if not self.detail_html:
    #                 self.detail_html = self.generate_html('detail')
    #     super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']


class Project(models.Model):
    name = models.CharField(max_length=25, blank=True,
                            help_text='25 characters max')
    geography = models.CharField(max_length=200, blank=True)
    description = models.TextField(max_length=2000, blank=True, )
    members_only = models.BooleanField(
        default=True, help_text='In order to post observations, you must have joined and been accepted into that project. For members-only projects, only members can view the data.')
    obs_types = models.ManyToManyField(ObservationType, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']


class Observation(models.Model):
    observer = models.ForeignKey('users.CustomUser',
                                 null=True, blank=True, related_name='observer',
                                 on_delete=models.SET_NULL)
    entered = models.DateTimeField(auto_now_add=True)
    # parentobs will be discarded in production
    # 'type' will be renamed 'obs_type' in production
    obs_type = models.ForeignKey(ObservationType, null=True, related_name='obs_type',
                                 on_delete=models.SET_NULL)
    site = models.ForeignKey(Site, related_name='site_observations',
                             on_delete=models.CASCADE)
    project = models.ForeignKey(
        Project, related_name='project_observations', null=True, blank=True, default=1, on_delete=models.CASCADE)
    # renamed from 'values'
    kv = JSONField(null=True, blank=True, help_text='must be valid JSON')

    def __str__(self):
        return '%s posted %s' % (self.obs_type, self.entered.date())

    def get_absolute_url(self):
        return "/observations/%i/" % self.id

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'observations'


class ObsComment(models.Model):
    author = models.ForeignKey('users.CustomUser',
                               null=True, blank=True, related_name='comment_author',
                               on_delete=models.CASCADE)
    observation = models.ForeignKey(Observation, null=True, related_name='observation',
                                    on_delete=models.CASCADE)
    entered = models.DateTimeField(auto_now_add=True)
    subject = models.CharField(max_length=100, blank=True)
    body = models.TextField(max_length=2000, blank=True)

    def __str__(self):
        return '%s posted %s by %s' % (self.subject, self.entered.date(), self.author)

templates/obs/index.html
{% extends '_base.html' %} 

{% block title %} 
Latest sites 
{% endblock title %}

{% block content %}

<h1>Latest Sites</h1>
{% if latest_site_list %}
<ul>
  {% for site in latest_site_list %}
  <li>
    <!-- this is an example of using a URL namespace, with a colon -->
    <a href="{% url 'obs:site_detail' site.id %}">{{ site.name }}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No sites are available.</p>
{% endif %} {% endblock %}

templates/obs/observation_detail.html
{% extends '_base.html' %} {% block title %} 
Observation detail 
{% endblock title %} {% block content %} {% if myobservation %}
<div class="container">
<h1>{{ myobservation }}</h1>

<p>Site: {{ myobservation.site }}</p>
<p>Geometry: {{ myobservation.site.geometry }}</p>

<p>Observer: {{ myobservation.observer }}</p>
<p>ObservationType: {{ myobservation.type }}</p>
<p>Entered: {{ myobservation.entered }}</p>


<ol>
{% comment %} using the items dictionary function to iterate JSON field {% endcomment %}
  {% for k, v in myobservation.kv.items %}
  <li><b>{{ k }}</b>: {{ v }}</li>
  {% endfor %}
</ol>

{% else %}

<p>Observation does not exist.</p>
{% endif %} 
</div>
{% endblock %}

templates/obs/observation_edit.html
{% extends '_base.html' %} {% block content %}
<h2>New Observation</h2>
<form method="POST" class="post-form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

templates/obs/observation_list.html
{% extends '_base.html' %} {% block content %}
<!-- {% load bootstrap %} -->

<div class="container">
<h2>Observation List</h2>
<form method="GET">
{{ filter.form|bootstrap }}
<button type="submit" class="btn btn-primary">Search</button>
</form>

{% if filter.qs %}
<ul>

    {% for obs in filter.qs %}
    <li>
        <a href="{% url 'obs:observation_detail' obs.id %}">{{ obs }}</a>
    </li>
    {% endfor %}

</ul>
{% else %}
<p>Sorry, no observations found for this query.</p>
{% endif %}
</div>






{% endblock %}

templates/obs/observe.html
{% extends '_base.html' %} {% block content %}

<h1>Make Observation on {{ site }}</h1>

{% if error_message %}
<p>
  <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'obs:observe' site.id %}" method="post">
  {% csrf_token %} {% for observation in site.observation_set.all %}
  <input
    type="text"
    name="observation"
    id="observation{{ forloop.counter }}"
    value="{{ observation.id }}"
  />
  <label for="observation{{ forloop.counter }}">{{ observation.data }}</label
  ><br />
  {% endfor %}
  <input type="submit" value="Observe" />
</form>
{% endblock %}

templates/obs/pointsite_list.html
{% extends '_base.html' %} {% block content %}

<h1>PointSites</h1>

<ul>
  {% for item in pointsite_list %}
  <li>{{ item.name }}</li>
  {% endfor %}
</ul>
{% include 'leaflet_point_map.html' %} {% endblock %}

templates/obs/search_results.html
{% extends '_base.html' %} {% block content %}
<p>this is in the obs app templates</p>
<h3>Search Results for</h3>
<ul>
  {% for el in object_list %}
  <li>
    {{ el }}
  </li>
  {% endfor %}
</ul>

{% endblock %}

templates/obs/site_detail.html
{% extends '_base.html' %} {% block content %}


<h1>{{ site.type }}</h1>

<p>{{ site }}</p>

{% include 'leaflet_map.html' %}
{% endblock %}

templates/obs/site_edit.html
{% extends '_base.html' %} {% block content %}
<h2>New Site</h2>
<form method="POST" class="post-form">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}